listKhodam = [
    { nama: "Harimau Putih", arti: "Kamu kuat dan berani seperti harimau, karena pendahulumu mewariskan kekuatan besar padamu." },
    { nama: "Panda Ompong", arti: "Kamu menggemaskan dan selalu berhasil membuat orang tersenyum dengan keanehanmu." },
    { nama: "Bebek Karet", arti: "Kamu selalu tenang dan ceria, mampu menghadapi gelombang masalah dengan senyum." },
    { nama: "Ninja Turtle", arti: "Kamu lincah dan tangguh, siap melindungi yang lemah dengan kekuatan tempurmu." },
    { nama: "Elang Terbang Tinggi", arti: "Kamu memiliki pandangan jauh ke depan dan kemampuan untuk mencapai puncak tertinggi." },
    { nama: "Singa Perkasa", arti: "Kamu adalah pemimpin alami dengan kekuatan dan keberanian luar biasa." },
    { nama: "Naga Api", arti: "Kamu penuh semangat dan energi yang membara, mampu mengatasi segala rintangan." },
    { nama: "Rusa Cepat", arti: "Kamu gesit dan tangkas, selalu bisa bergerak cepat dalam situasi apapun." },
    { nama: "Serigala Bijak", arti: "Kamu memiliki kecerdasan dan kebijaksanaan yang membantu kamu dalam membuat keputusan penting." },
    { nama: "Penyu Tangguh", arti: "Kamu kuat dan tahan banting, mampu bertahan dalam situasi sulit." },
    { nama: "Merpati Damai", arti: "Kamu membawa kedamaian dan keharmonisan di mana pun kamu berada." },
    { nama: "Gajah Setia", arti: "Kamu setia dan memiliki loyalitas yang tinggi terhadap teman dan keluarga." },
    { nama: "Kucing Hitam", arti: "Kamu misterius dan penuh pesona, selalu menarik perhatian orang lain." },
    { nama: "Buaya Sungai", arti: "Kamu penuh strategi dan ketekunan dalam mencapai tujuanmu." },
    { nama: "Burung Hantu", arti: "Kamu bijaksana dan memiliki pengetahuan yang mendalam." },
    { nama: "Kuda Pusaran", arti: "Kamu memiliki semangat yang tak terbendung dan selalu bergerak maju." },
    { nama: "Leopard Cepat", arti: "Kamu cepat dan efisien dalam melakukan setiap tugas." },
    { nama: "Ikan Lumba", arti: "Kamu penuh kegembiraan dan membawa keceriaan di sekitar." },
    { nama: "Kupu-Kupu Cantik", arti: "Kamu anggun dan penuh keindahan, selalu membuat orang terpesona." },
    { nama: "Kera Pintar", arti: "Kamu cerdas dan selalu menemukan cara baru untuk menyelesaikan masalah." },
    { nama: "Burung Merah", arti: "Kamu penuh energi dan semangat yang menggebu-gebu." },
    { nama: "Gajah Besar", arti: "Kamu memiliki kekuatan dan kehadiran yang luar biasa." },
    { nama: "Harimau Kecil", arti: "Kamu penuh semangat dan berani meskipun dalam ukuran yang kecil." },
    { nama: "Kuda Hitam", arti: "Kamu penuh misteri dan selalu mengejutkan orang dengan kemampuanmu." },
    { nama: "Ikan Terbang", arti: "Kamu bebas dan selalu mencari petualangan baru." },
    { nama: "Burung Hantu Putih", arti: "Kamu bijaksana dan selalu mencari kebenaran dalam segala hal." },
    { nama: "Singa Muda", arti: "Kamu penuh potensi dan siap untuk menguasai dunia." },
    { nama: "Rubah Licik", arti: "Kamu pintar dan selalu memiliki rencana cadangan." },
    { nama: "Kucing Anggun", arti: "Kamu elegan dan selalu bertindak dengan penuh kehormatan." },
    { nama: "Ikan Hiu", arti: "Kamu penuh kekuatan dan keberanian di dalam menghadapi tantangan." },
    { nama: "Ular Gesit", arti: "Kamu lincah dan selalu siap menghadapi situasi apapun." },
    { nama: "Burung Elang", arti: "Kamu memiliki pandangan jauh ke depan dan tekad yang kuat." },
    { nama: "Singa Besar", arti: "Kamu memiliki kekuatan dan keberanian yang luar biasa." },
    { nama: "Harimau Hitam", arti: "Kamu penuh misteri dan kekuatan yang tak terduga." },
    { nama: "Kuda Putih", arti: "Kamu anggun dan penuh dengan semangat juang." },
    { nama: "Ikan Paus", arti: "Kamu besar dan penuh dengan kebijaksanaan." },
    { nama: "Kura-Kura", arti: "Kamu sabar dan penuh dengan ketekunan." },
    { nama: "Burung Beo", arti: "Kamu penuh dengan kecerdasan dan kemampuan berbicara." },
    { nama: "Gajah Muda", arti: "Kamu kuat dan penuh dengan semangat muda." },
    { nama: "Harimau Cilik", arti: "Kamu kecil namun penuh dengan keberanian dan kekuatan." },
    { nama: "Kuda Coklat", arti: "Kamu penuh dengan kekuatan dan ketahanan." },
    { nama: "Ikan Kecil", arti: "Kamu kecil namun penuh dengan semangat hidup." },
    { nama: "Rusa Hutan", arti: "Kamu lincah dan selalu waspada terhadap lingkungan sekitar." },
    { nama: "Merpati Putih", arti: "Kamu pembawa kedamaian dan harmoni di sekitar kamu." },
    { nama: "Burung Rajawali", arti: "Kamu memiliki pandangan tajam dan kecepatan yang luar biasa." },
    { nama: "Kucing Lucu", arti: "Kamu penuh dengan keceriaan dan membuat orang lain senang." },
    { nama: "Serigala Hitam", arti: "Kamu penuh dengan misteri dan kekuatan yang tersembunyi." },
    { nama: "Harimau Merah", arti: "Kamu penuh dengan semangat dan keberanian yang menyala-nyala." },
    { nama: "Gajah Besar", arti: "Kamu penuh dengan kekuatan dan ketahanan yang luar biasa." },
    { nama: "Singa Kecil", arti: "Kamu kecil namun penuh dengan keberanian dan tekad." },
    { nama: "Rusa Anggun", arti: "Kamu penuh dengan keanggunan dan kelincahan." },
    { nama: "Ikan Terang", arti: "Kamu membawa cahaya dan keceriaan di mana pun kamu berada." },
    { nama: "Kupu-Kupu Cerah", arti: "Kamu penuh dengan keceriaan dan keindahan." },
    { nama: "Ular Panjang", arti: "Kamu penuh dengan kebijaksanaan dan kemampuan beradaptasi." },
    { nama: "Kuda Kuat", arti: "Kamu penuh dengan kekuatan dan ketahanan yang luar biasa." },
    { nama: "Burung Hantu Hitam", arti: "Kamu penuh dengan kebijaksanaan dan misteri." },
    { nama: "Singa Tangguh", arti: "Kamu penuh dengan kekuatan dan keberanian yang luar biasa." },
    { nama: "Rusa Muda", arti: "Kamu penuh dengan semangat dan kelincahan." },
    { nama: "Harimau Besar", arti: "Kamu penuh dengan kekuatan dan keberanian yang luar biasa." },
    { nama: "Ikan Lincah", arti: "Kamu penuh dengan kelincahan dan ketangkasan." },
    { nama: "Kupu-Kupu Anggun", arti: "Kamu penuh dengan keanggunan dan keindahan." },
    { nama: "Kuda Tangguh", arti: "Kamu penuh dengan kekuatan dan ketahanan yang luar biasa." },
    { nama: "Gajah Putih", arti: "Kamu penuh dengan kebijaksanaan dan keagungan." },
    { nama: "Serigala Cerdik", arti: "Kamu penuh dengan kecerdikan dan kelicikan." },
    { nama: "Burung Hantu Muda", arti: "Kamu penuh dengan kebijaksanaan dan pengetahuan." },
    { nama: "Harimau Muda", arti: "Kamu penuh dengan semangat dan keberanian yang luar biasa." },
    { nama: "Ikan Besar", arti: "Kamu penuh dengan kekuatan dan kebijaksanaan yang luar biasa." },
    { nama: "Kucing Gesit", arti: "Kamu penuh dengan kelincahan dan ketangkasan." },
    { nama: "Burung Elang Muda", arti: "Kamu penuh dengan semangat dan kecepatan yang luar biasa." },
    { nama: "Ayam Terbang", arti: "Kamu penuh kejutan dan bisa melakukan hal-hal yang tidak terduga, seperti ayam yang tiba-tiba bisa terbang." },
    { nama: "Kelinci Jagoan", arti: "Kamu kecil namun berani dan tidak pernah takut menghadapi tantangan, seperti kelinci yang menjadi jagoan." },
    { nama: "Katak Kungfu", arti: "Kamu lincah dan ahli dalam berbagai hal, seperti katak yang bisa beraksi dengan gerakan kungfu." },
    { nama: "Bebek Joget", arti: "Kamu selalu membawa keceriaan dan bisa membuat orang lain tertawa, seperti bebek yang selalu ingin joget." },
    { nama: "Kucing Lucu", arti: "Kamu selalu berhasil menarik perhatian orang dengan kelucuanmu, seperti kucing yang selalu menggemaskan." },
    { nama: "Burung Ngomong", arti: "Kamu selalu bisa menirukan suara-suara lucu dan membuat suasana jadi menyenangkan, seperti burung yang bisa ngomong." },
    { nama: "Tikus Lincah", arti: "Kamu gesit dan cepat dalam segala hal, seperti tikus yang selalu lincah bergerak." },
    { nama: "Kambing Guling", arti: "Kamu suka berpetualang dan mencoba hal-hal baru, seperti kambing yang bisa berguling." },
    { nama: "Anjing Gendut", arti: "Kamu penuh dengan kasih sayang dan selalu membuat orang lain merasa nyaman, seperti anjing yang gendut dan menggemaskan." },
    { nama: "Babi Ngepet", arti: "Kamu penuh trik dan selalu bisa menemukan cara untuk mendapatkan apa yang kamu inginkan, seperti babi yang bisa ngepet." },
    { nama: "Kuda Tertawa", arti: "Kamu selalu membawa keceriaan dan bisa membuat orang lain tertawa, seperti kuda yang tertawa." },
    { nama: "Ikan Terbang", arti: "Kamu selalu penuh kejutan dan bisa melakukan hal-hal yang tidak terduga, seperti ikan yang bisa terbang." },
    { nama: "Sapi Lucu", arti: "Kamu selalu berhasil membuat orang lain tertawa dengan tingkah lakumu, seperti sapi yang lucu." },
    { nama: "Kucing Ninja", arti: "Kamu lincah dan selalu bisa bergerak tanpa terlihat, seperti kucing yang menjadi ninja." },
    { nama: "Burung Gokil", arti: "Kamu penuh dengan kegilaan dan selalu bisa membuat suasana jadi seru, seperti burung yang gokil." },
    { nama: "Kambing Nyengir", arti: "Kamu selalu tersenyum dan bisa membuat orang lain ikut bahagia, seperti kambing yang nyengir." },
    { nama: "Kucing Super", arti: "Kamu memiliki kekuatan luar biasa dan selalu siap membantu, seperti kucing yang punya kekuatan super." },
    { nama: "Ayam Berkokok", arti: "Kamu selalu bersemangat dan bisa membangunkan semangat orang lain, seperti ayam yang berkokok setiap pagi." },
    { nama: "Bebek Gaul", arti: "Kamu selalu tampil modis dan mengikuti tren, seperti bebek yang gaul." },
    { nama: "Kuda Kocak", arti: "Kamu selalu bisa membuat orang lain tertawa dengan kekocakanmu, seperti kuda yang kocak." },
    { nama: "Burung Ketawa", arti: "Kamu penuh dengan keceriaan dan selalu bisa membuat orang lain tertawa, seperti burung yang ketawa." },
    { nama: "Sapi Joget", arti: "Kamu selalu membawa keceriaan dan bisa membuat suasana jadi meriah, seperti sapi yang bisa joget." },
    { nama: "Kelinci Kungfu", arti: "Kamu lincah dan selalu siap menghadapi tantangan, seperti kelinci yang bisa kungfu." },
    { nama: "Bebek Tertawa", arti: "Kamu penuh dengan keceriaan dan selalu bisa membuat orang lain tertawa, seperti bebek yang tertawa." },
    { nama: "Tikus Pintar", arti: "Kamu cerdas dan selalu punya cara untuk menyelesaikan masalah, seperti tikus yang pintar." },
    { nama: "Burung Gaul", arti: "Kamu selalu tampil modis dan menjadi pusat perhatian, seperti burung yang gaul." },
    { nama: "Kucing Aneh", arti: "Kamu unik dan selalu berhasil menarik perhatian orang dengan tingkah lakumu yang aneh, seperti kucing yang aneh." },
    { nama: "Ayam Super", arti: "Kamu memiliki kekuatan luar biasa dan selalu siap membantu, seperti ayam yang punya kekuatan super." },
    { nama: "Kelinci Gokil", arti: "Kamu penuh dengan kegilaan dan selalu bisa membuat suasana jadi seru, seperti kelinci yang gokil." },
    { nama: "Anjing Tertawa", arti: "Kamu penuh dengan keceriaan dan selalu bisa membuat orang lain tertawa, seperti anjing yang tertawa." },
    { nama: "Kucing Gaul", arti: "Kamu selalu tampil modis dan mengikuti tren, seperti kucing yang gaul." },
    { nama: "Kambing Gokil", arti: "Kamu penuh dengan kegilaan dan selalu bisa membuat suasana jadi seru, seperti kambing yang gokil." },
    { nama: "Burung Lucu", arti: "Kamu selalu berhasil membuat orang lain tertawa dengan tingkah lakumu, seperti burung yang lucu." },
    { nama: "Ayam Ninja", arti: "Kamu lincah dan selalu bisa bergerak tanpa terlihat, seperti ayam yang menjadi ninja." },
    { nama: "Sapi Tertawa", arti: "Kamu penuh dengan keceriaan dan selalu bisa membuat orang lain tertawa, seperti sapi yang tertawa." },
    { nama: "Kelinci Gaul", arti: "Kamu selalu tampil modis dan mengikuti tren, seperti kelinci yang gaul." },
    { nama: "Kucing Kocak", arti: "Kamu selalu bisa membuat orang lain tertawa dengan kekocakanmu, seperti kucing yang kocak." },
    { nama: "Ayam Joget", arti: "Kamu selalu membawa keceriaan dan bisa membuat suasana jadi meriah, seperti ayam yang bisa joget." },
    { nama: "Kuda Gaul", arti: "Kamu selalu tampil modis dan menjadi pusat perhatian, seperti kuda yang gaul." },
    { nama: "Kelinci Lucu", arti: "Kamu selalu berhasil membuat orang lain tertawa dengan tingkah lakumu, seperti kelinci yang lucu." },
    { nama: "Tikus Gaul", arti: "Kamu selalu tampil modis dan mengikuti tren, seperti tikus yang gaul." },
    { nama: "Burung Pintar", arti: "Kamu cerdas dan selalu punya cara untuk menyelesaikan masalah, seperti burung yang pintar." },
    { nama: "Kucing Pahlawan", arti: "Kamu selalu siap membantu dan menjadi pahlawan, seperti kucing yang menjadi pahlawan." },
    { nama: "Ayam Kocak", arti: "Kamu selalu bisa membuat orang lain tertawa dengan kekocakanmu, seperti ayam yang kocak." },
    { nama: "Sapi Gaul", arti: "Kamu selalu tampil modis dan menjadi pusat perhatian, seperti sapi yang gaul." },
    { nama: "Burung Gila", arti: "Kamu penuh dengan kegilaan dan selalu bisa membuat suasana jadi seru, seperti burung yang gila." },
    { nama: "Tikus Kocak", arti: "Kamu selalu bisa membuat orang lain tertawa dengan kekocakanmu, seperti tikus yang kocak." },
    { nama: "Kelinci Tertawa", arti: "Kamu penuh dengan keceriaan dan selalu bisa membuat orang lain tertawa, seperti kelinci yang tertawa." },
    { nama: "Ayam Jago Selfie", arti: "Kamu selalu siap tampil dan menarik perhatian, seperti ayam jago yang suka selfie." },
    { nama: "Kucing Tidur Siang", arti: "Kamu selalu tahu cara bersantai dan menikmati waktu luang, seperti kucing yang suka tidur siang." },
    { nama: "Sapi Ngopi", arti: "Kamu selalu santai dan menikmati setiap momen, seperti sapi yang suka ngopi." },
    { nama: "Anjing Main PS", arti: "Kamu selalu mencari cara untuk bersenang-senang, seperti anjing yang suka main PlayStation." },
    { nama: "Bebek Nonton TV", arti: "Kamu selalu update dengan hiburan terbaru, seperti bebek yang suka nonton TV." },
    { nama: "Tikus Pesta Keju", arti: "Kamu selalu siap merayakan setiap momen, seperti tikus yang suka pesta keju." },
    { nama: "Gajah Melukis", arti: "Kamu kreatif dan selalu menemukan cara baru untuk mengekspresikan diri, seperti gajah yang bisa melukis." },
    { nama: "Kuda Lari Cepat", arti: "Kamu selalu siap bergerak dan mencapai tujuan dengan cepat, seperti kuda yang lari cepat." },
    { nama: "Burung Karaoke", arti: "Kamu selalu penuh semangat dan suka bernyanyi, seperti burung yang suka karaoke." },
    { nama: "Kelinci Loncat-loncat", arti: "Kamu selalu energik dan penuh semangat, seperti kelinci yang suka loncat-loncat." },
    { nama: "Harimau Bersepeda", arti: "Kamu selalu aktif dan suka berpetualang, seperti harimau yang suka bersepeda." },
    { nama: "Kuda Pacu", arti: "Kamu selalu bergerak cepat dan fokus pada tujuan, seperti kuda pacu." },
    { nama: "Katak Berenang", arti: "Kamu selalu lincah dan suka berolahraga, seperti katak yang suka berenang." },
    { nama: "Burung Bersiul", arti: "Kamu selalu riang dan penuh dengan keceriaan, seperti burung yang suka bersiul." },
    { nama: "Ikan Menari", arti: "Kamu selalu bergerak dengan gaya dan suka menari, seperti ikan yang suka menari." },
    { nama: "Tikus Mengendap-endap", arti: "Kamu selalu hati-hati dan cermat, seperti tikus yang suka mengendap-endap." },
    { nama: "Ayam Ngambek", arti: "Kamu selalu tahu kapan harus berhenti dan tidak dipaksakan, seperti ayam yang suka ngambek." },
    { nama: "Sapi Berdasi", arti: "Kamu selalu tampil rapi dan siap menghadapi dunia, seperti sapi yang suka berdasi." },
    { nama: "Kelinci Berkacamata", arti: "Kamu selalu pintar dan suka belajar, seperti kelinci yang suka berkacamata." },
    { nama: "Kucing Bermalas-malas", arti: "Kamu selalu tahu cara bersantai dan menikmati hidup, seperti kucing yang suka bermalas-malas." },
    { nama: "Gajah Berpesta", arti: "Kamu selalu tahu cara merayakan dan bersenang-senang, seperti gajah yang suka berpesta." },
    { nama: "Bebek Main Air", arti: "Kamu selalu menikmati setiap momen dan suka bermain, seperti bebek yang suka main air." },
    { nama: "Harimau Yoga", arti: "Kamu selalu menjaga keseimbangan dan kesehatan, seperti harimau yang suka yoga." },
    { nama: "Burung Melompat", arti: "Kamu selalu energik dan suka mencoba hal baru, seperti burung yang suka melompat." },
    { nama: "Kuda Menari", arti: "Kamu selalu bergerak dengan elegan dan suka menari, seperti kuda yang suka menari." },
    { nama: "Anjing Berjemur", arti: "Kamu selalu tahu cara menikmati sinar matahari dan bersantai, seperti anjing yang suka berjemur." },
    { nama: "Ikan Bermain Air", arti: "Kamu selalu menikmati setiap momen dan suka bermain, seperti ikan yang suka bermain air." },
    { nama: "Kucing Mendengkur", arti: "Kamu selalu tahu cara bersantai dan menikmati waktu istirahat, seperti kucing yang suka mendengkur." },
    { nama: "Ayam Berdandan", arti: "Kamu selalu tampil modis dan siap menghadapi dunia, seperti ayam yang suka berdandan." },
    { nama: "Tikus Menggali", arti: "Kamu selalu mencari cara untuk menemukan hal baru, seperti tikus yang suka menggali." },
    { nama: "Kelinci Melompat", arti: "Kamu selalu energik dan penuh semangat, seperti kelinci yang suka melompat." },
    { nama: "Burung Berkicau", arti: "Kamu selalu riang dan penuh dengan keceriaan, seperti burung yang suka berkicau." },
    { nama: "Gajah Bersepeda", arti: "Kamu selalu aktif dan suka berpetualang, seperti gajah yang suka bersepeda." },
    { nama: "Kuda Berlari", arti: "Kamu selalu bergerak cepat dan fokus pada tujuan, seperti kuda yang suka berlari." },
    { nama: "Katak Lompat-lompat", arti: "Kamu selalu lincah dan penuh dengan energi, seperti katak yang suka lompat-lompat." },
    { nama: "Harimau Mengaum", arti: "Kamu selalu penuh semangat dan tidak takut menunjukkan keberanian, seperti harimau yang suka mengaum." },
    { nama: "Sapi Menari", arti: "Kamu selalu bergerak dengan gaya dan suka menari, seperti sapi yang suka menari." },
    { nama: "Ayam Berkotek", arti: "Kamu selalu penuh dengan keceriaan dan suka berbicara, seperti ayam yang suka berkotek." },
    { nama: "Burung Bersenandung", arti: "Kamu selalu riang dan penuh dengan keceriaan, seperti burung yang suka bersenandung." },
    { nama: "Kucing Bermain Bola", arti: "Kamu selalu aktif dan suka bermain, seperti kucing yang suka bermain bola." },
    { nama: "Ikan Menggelitik", arti: "Kamu selalu membawa keceriaan dan suka membuat orang lain tertawa, seperti ikan yang suka menggelitik." },
    { nama: "Tikus Berpetualang", arti: "Kamu selalu mencari petualangan dan suka menjelajahi hal baru, seperti tikus yang suka berpetualang." },
    { nama: "Kelinci Berkeliling", arti: "Kamu selalu penasaran dan suka menjelajahi tempat baru, seperti kelinci yang suka berkeliling." },
    { nama: "Anjing Menggonggong", arti: "Kamu selalu penuh semangat dan suka menunjukkan keberanian, seperti anjing yang suka menggonggong." },
    { nama: "Sapi Makan Rumput", arti: "Kamu selalu menikmati hal-hal sederhana dalam hidup, seperti sapi yang suka makan rumput." },
    { nama: "Burung Terbang Tinggi", arti: "Kamu selalu memiliki cita-cita tinggi dan berusaha mencapainya, seperti burung yang suka terbang tinggi." },
    { nama: "Kucing Penasaran", arti: "Kamu selalu ingin tahu dan suka menjelajahi hal baru, seperti kucing yang selalu penasaran." },
    { nama: "Tikus Berlari", arti: "Kamu selalu bergerak cepat dan suka berpetualang, seperti tikus yang suka berlari." }
];